# Build stage for Windows
FROM golang:1.25.4-windowsservercore AS build
ARG VERSION="dev"

WORKDIR /build

COPY go.mod go.sum ./
COPY cmd ./cmd
COPY internal ./internal
COPY pkg ./pkg

RUN go build -ldflags="-s -w" -o github-mcp-server.exe cmd/github-mcp-server/main.go

# Final stage
FROM mcr.microsoft.com/windows/servercore:ltsc2022
WORKDIR /server
COPY --from=build /build/github-mcp-server.exe .
ENTRYPOINT ["github-mcp-server.exe"]
CMD ["stdio"]
